version: '3.7'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
